### ISSUE TITLE
Server 500 error when uploading large file (=2.5GB)

### ISSUE THREAD

**Issue by mgardnerpsu** [Duke-Translational-Bioinformatics/duke-data-service#292]
An internal server error is returned (HTTP 500) when I try to upload file with a size of 2.5GB - appears the ActiveRecord type for "upload.size" cannot accept this many bytes; Heroku log details:

2016-01-08T19:22:01.628076+00:00 app[web.1]: RangeError (2621445088 is out of range for ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer with limit 4):
2016-01-08T19:22:01.628077+00:00 app[web.1]:   app/api/dds/v1/uploads_api.rb:47:in `block (4 levels) in <class:UploadsAPI>'
2016-01-08T19:22:01.628078+00:00 app[web.1]:   app/api/dds/v1/uploads_api.rb:33:in `block (3 levels) in <class:UploadsAPI>'
2016-01-08T19:22:01.628078+00:00 app[web.1]: 
2016-01-08T19:22:01.628079+00:00 app[web.1]: 
2016-01-08T19:22:01.658314+00:00 heroku[router]: at=info method=POST path="/api/v1/projects/ee5e190a-80f5-406a-b8ec-8372ab12e505/uploads" host=dev.dataservice.duke.edu request_id=da2cab9f-d186-4611-9849-e215adb393c3 fwd="152.16.191.31" dyno=web.1 connect=2ms service=94ms status=500 bytes=343

**Comment by dmlond** [comment]
on monday we can change it to a bigint

http://www.postgresql.org/docs/9.1/static/datatype-numeric.html
